name: Build and Push Docker Image to Dokcer Hub

on:
  push:
    branches:
      - master
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: list go go-version
        run: go version
      - name: Install dependencies
        run: go mod tidy

      - name: Build the go project
        run: go build cmd/api/main.go

      - name: Run All unit test
        run: go test -v ./...
  push_to_registry:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      docker_image_tagged: ${{ steps.vars.outputs.docker_image_tagged }}
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.BRANCH_NAME }}-${{ steps.vars.outputs.sha_short }}
          context: .
          file: ./Dockerfile
